/*
 * This file is generated by jOOQ.
 */
package com.example.db;

import org.jooq.Record;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public interface CustomPropertyValueRecord extends Record {

    public Long getObjectId();

    public void setObjectId(Long value);

    public Long getCustomPropertyId();

    public void setCustomPropertyId(Long value);

    public Long getLongValue();

    public void setLongValue(Long value);

    public Integer getIntegerValue();

    public void setIntegerValue(Integer value);

    public Double getDoubleValue();

    public void setDoubleValue(Double value);

    public Boolean getBooleanValue();

    public void setBooleanValue(Boolean value);

    public String getStringValue();

    public void setStringValue(String value);
}
