POST localhost:8080/person/

###

# localhost:8080/person/{id}/cp/{code}
GET localhost:8080/person/1/cp/CODE_SIZE

###

# localhost:8080/person/{id}/cp/{code}
GET localhost:8080/person/1/cp

###

POST localhost:8080/person/1/cp
Content-type: application/json

{
  "code": "NEW_CP_CODE234",
  "value": 121
}

###

PUT localhost:8080/person/1/cp
Content-type: application/json

{
  "code": "CODE_SIZE_2",
  "value": "CREATE_OR_UPDATE"
}



