POST localhost:8080/person/

###

# localhost:8080/item/{id}/cp/{code}
GET localhost:8080/person/1/cp/CODE_SIZE

###

POST localhost:8080/person/1/cp
Content-type: application/json

{
  "code": "CODE_SIZE",
  "value": "NEW_VALUE"
}

###

PUT localhost:8080/person/1/cp
Content-type: application/json

{
  "code": "CODE_SIZE_2",
  "value": "CREATE_OR_UPDATE"
}

